[package]
name = "deesse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nt_utils = { git = "https://github.com/hrafnskogr/nt_utils" }
sha256 = "1.0.3"

[build-dependencies]
rand = "0.8.5"
