
/*
 *
 * FILE AUTOGENERATED BY build.rs
 *
 */

pub mod asmcalls;
pub mod ntcalls;
pub mod err;
pub mod oncecell;

use oncecell::*;
use ntcalls::*;

// Reexports the assembly direct calls skeletons 
// for cleaner use
pub use crate::asmcalls::*;

pub static SALT: &str = "2fa1e3123496e3f91e9b93e1583adae4";
pub static NT: OnceCell<NTApi> = OnceCell::new(|| {NTApi::new().unwrap()} );
